// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDypq6gqHwVpknUWb4eM-5mUJtrvq6GgqY',
    appId: '1:128357502670:web:1d145f13636fc923d14a9f',
    messagingSenderId: '128357502670',
    projectId: 'firedetect-52cc8',
    authDomain: 'firedetect-52cc8.firebaseapp.com',
    databaseURL: 'https://firedetect-52cc8-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'firedetect-52cc8.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBl8pVRV9eUEsSvlShwwHaBCLfWGz1ZNFE',
    appId: '1:128357502670:android:5caeaa5d2c91366dd14a9f',
    messagingSenderId: '128357502670',
    projectId: 'firedetect-52cc8',
    databaseURL: 'https://firedetect-52cc8-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'firedetect-52cc8.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCknlsxR0NI1nyF8yfTct2ZRMCqTPU2JA8',
    appId: '1:128357502670:ios:d727fedc316174b7d14a9f',
    messagingSenderId: '128357502670',
    projectId: 'firedetect-52cc8',
    databaseURL: 'https://firedetect-52cc8-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'firedetect-52cc8.firebasestorage.app',
    iosBundleId: 'com.example.fireProtect',
  );
}
